version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: collab_postgres
    restart: always
    environment:
      POSTGRES_DB: collab_db
      POSTGRES_USER: collab_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
